### ISSUE TITLE
Trouble with Node > 10

### ISSUE THREAD

**Issue by tschaub** [hegemonic/requizzle#6]
I haven't been able to nail down the specifics, but it looks like this module fails (as used by JSDoc) on Node > 10, perhaps only on linux.

See https://github.com/jsdoc3/jsdoc/issues/1530#issuecomment-487311288 for one report.

We're seeing CI failures with this stack:
```
/home/circleci/repo/node_modules/requizzle/lib/requizzle.js:45
	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
	               ^

TypeError: Cannot read property '0' of null
    at isNativeModule (/home/circleci/repo/node_modules/requizzle/lib/requizzle.js:45:17)
    at Requizzle.requizzle (/home/circleci/repo/node_modules/requizzle/lib/requizzle.js:82:6)
    at infectProxy (/home/circleci/repo/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/home/circleci/repo/node_modules/requizzle/lib/loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/circleci/repo/node_modules/jsdoc/lib/jsdoc/fs.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Object.load (/home/circleci/repo/node_modules/requizzle/lib/loader.js:112:15)
```

I'll try to get more detail.

**Comment by hegemonic** [comment]
This should be working on master thanks to #4. New release (of this package and JSDoc) later this week, hopefully. Apologies for the breakage and delay.

**Comment by tschaub** [comment]
Thanks @hegemonic.
