### ISSUE TITLE
No longer working on Node v6

### ISSUE THREAD

**Issue by mbrune-sharecare** [hegemonic/requizzle#7]
Recent changes with the removal of 'use strict' have seemingly caused runtime errors for my services such as:

```
{"time":"1557156036","priority":"ERROR","class":"SCExpressJS","data":"{` JSDOC_ERROR: /opt/applications/component-api/node_modules/requizzle/index.js:11
    let instance;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /opt/applications/component-api/node_modules/jsdoc-75lb/jsdoc.js:25:19
    at Object.<anonymous> (/opt/applications/component-api/node_modules/jsdoc-75lb/jsdoc.js:35:3)
    at Module._compile (module.js:409:26)
    at Explain.verifyOutput (/opt/applications/component-api/node_modules/jsdoc-api/lib/jsdoc-command.js:108:19)
    at ChildProcess.handle.on.err (/opt/applications/component-api/node_modules/jsdoc-api/lib/explain.js:48:38)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close (net.js:498:12)
    at Pipe._onclose (/opt/applications/component-api/node_modules/async-listener/glue.js:188:31) name: 'JSDOC_ERROR', 'error@context': {} }"}
```

Any reason why this seemingly breaking change was done as a patch bump and not as a minor version bump? Or is there a quick solution? We are looking at upgrading from Node v6 at the moment to v8 or higher but not sure when we will able to.

**Comment by dargmuesli** [comment]
My PR CI builds fail too for that reason: https://travis-ci.org/jsdoc2md/jsdoc-api/jobs/528647141

**Comment by hegemonic** [comment]
From the [semver 2.0.0 spec](https://semver.org/spec/v2.0.0.html):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

JSDoc was around before semver was a thing, and it has not historically used semver for releases. That's why the [`README`](https://github.com/jsdoc/jsdoc) encourages you to pin to a minor version (e.g., `"jsdoc": "~3.5.5"`), not a major version (e.g., `"jsdoc": "^3.5.5"`).
